version: '3.7'

services:
  diid:
    build:
      context: .
      dockerfile: Dockerfile
    image: distinctid
    restart: always
    container_name: c_diid
    command: daemon
    environment:
      SHARD_ID: $SHARD_ID
      SCALE_WORKERS: $SCALE_WORKERS
    ports:
    - $SUPERVISOR_IP:9001
    - $WEB_IP:8000
