version: '3.7'

services:
  diid:
    build:
      context: .
      dockerfile: Dockerfile
    image: distinctid
    restart: always
    container_name: c_diid
    command: daemon
    environment:
      SHARD_ID: $SHARD_ID
      GUNICORN_WORKERS: $GUNICORN_WORKERS
      JSON_RESPONSE: $JSON_RESPONSE
    ports:
    - $SUPERVISOR_IP:9001
    - $WEB_IP:8000
